name: DevOps
on:
  push:
    branches: ['master', 'develop', 'release-*']

jobs:
  devops:
    name: Test - Unit & SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run tests and generate coverage
        run: npm test -- --code-coverage --browsers=ChromeHeadless

      - name: SonarCloud Scan
        run: npx sonar-scanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
